In [3]:
import numpy as np
import scipy.special
import cvxpy as cp

from scipy.optimize import minimize

# Importing standard Qiskit libraries
from qiskit import QuantumCircuit, ClassicalRegister, QuantumRegister, transpile, Aer, IBMQ, execute
from qiskit.circuit import Parameter
from qiskit.tools.jupyter import *
from qiskit.visualization import *
#from ibm_quantum_widgets import *
from qiskit.providers.aer import QasmSimulator

from src import QAOA_utilities as QAOAut
from src import CellFreeQAOA as CFQAOA

# Loading your IBM Quantum account(s)
#provider = IBMQ.load_account()

ModuleNotFoundError: No module named 'cvxpy'

In [2]:
M = 3 # number of cells
K = 3 # number of users
rho = 1 # max power
BW_max = 6 # max BW, M_hat in paper
rng = np.random.default_rng(2703)
#eta = np.random.rand(K) # power control fraction for each user
#alpha = np.random.rand(M,K)
#beta = np.random.rand(M,K)
eta = rng.random(K) # power control fraction for each user TO BE OTPIMIZED
alpha = rng.random((M,K))
beta = rng.random((M,K))
t = 1

In [3]:
t = 1
eta = rng.random(K) 

tol_global = 10**(-7)
maxiter = 10
ti = t
tf = t + 2*tol_global
glit = 0

while( abs(tf - ti) > tol_global and glit < maxiter ):
    print('Starting iteration n° ',glit,' - current intra-iteration difference: ', abs(tf - ti))
    glit += 1
    ti = t
    X_mat , t = CFQAOA.bruteforce_SINR(M, K, BW_max, eta, alpha, beta, rho)
    eta, t = CFQAOA.optimize_powers(rho, X_mat, alpha, beta, t)
    tf = t
    
print('Current intra-iteration difference: ', abs(tf - ti))
X_opt = X_mat
t_opt = t
eta_opt = eta

Starting iteration n°  0  - current intra-iteration difference:  1.9999999989472883e-07
Actual full search best

ID:  234
MIN SINR:  0.39211926894246324
Best X:  [[0. 1. 1.]
 [1. 0. 1.]
 [1. 0. 1.]]
----- Starting Bisection Method -----
D E B U G   --->    1 [[0. 1. 1.]
 [1. 0. 1.]
 [1. 0. 1.]] [[0.45313096 0.94245015 0.44214828]
 [0.55604655 0.00476601 0.25644698]
 [0.91350184 0.60888821 0.18735454]] [[0.8967107  0.70395423 0.63848526]
 [0.04027483 0.77438865 0.85281433]
 [0.80659107 0.17065088 0.55676482]] 0.43454407194436373
Optimal t =  0.43454407194436373
Optimal eta =  [0.60711284 0.99999995 0.97797167]
Starting iteration n°  1  - current intra-iteration difference:  0.5654559280556363
Actual full search best

ID:  234
MIN SINR:  0.43454408229195046
Best X:  [[0. 1. 1.]
 [1. 0. 1.]
 [1. 0. 1.]]
----- Starting Bisection Method -----
D E B U G   --->    1 [[0. 1. 1.]
 [1. 0. 1.]
 [1. 0. 1.]] [[0.45313096 0.94245015 0.44214828]
 [0.55604655 0.00476601 0.25644698]
 [0.91350184 0.6088

In [4]:
t = 1
eta = rng.random(K) 

tol_global = 10**(-7)
maxiter = 10
ti = t
tf = t + 2*tol_global
glit = 0

while( abs(tf - ti) > tol_global and glit < maxiter ):
    print('Starting iteration n° ',glit,' - current intra-iteration difference: ', abs(tf - ti))
    glit += 1
    ti = t
    X_mat, t, QAOA_xt = CFQAOA.optimize_links(BW_max, rho, eta, alpha, beta, t)
    QAOA_X, QAOA_t = X_mat, t
    eta, t = CFQAOA.optimize_powers(rho, X_mat, alpha, beta, t)
    tf = t
    
print('Current intra-iteration difference: ', abs(tf - ti))

Starting iteration n°  0  - current intra-iteration difference:  1.9999999989472883e-07


TypeError: optimize_links() missing 2 required positional arguments: 'lambda_0' and 'tg'

In [ ]:
def check_SINR(X, t, alpha, beta, rho, eta):
    snr = CFQAOA.SINR(X, eta, alpha, beta, rho )
    print(snr)
    return(snr > t)

In [ ]:
check_SINR(X_mat, t, alpha, beta, rho, eta)

In [ ]:
check_SINR(X_opt, t_opt, alpha, beta, rho, eta_opt)